# Generated by Django 5.1 on 2024-09-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
