# Generated by Django 5.1 on 2024-09-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_rename_stock_cafe_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
